### ISSUE TITLE
How to query an image file?

### ISSUE THREAD

**Issue by newyangyang** [qf6101/tensorflow_serving_examples#2]
This project works for me . But it consumes a file containing many images.  How can I adapt your code to work with one image file?

**Comment by qf6101** [comment]
Please refer to the following usage.
https://github.com/qf6101/tensorflow_serving_examples/blob/81aacf3b3cfc2caa3cd7310a49a237992046eb27/src/main/java/io/github/qf6101/tensorflowserving/MNISTJavaClient.java#L63-L64
